name: Build

on: [push, pull_request]

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:20250102

    steps:
    - name: Checkout udpih
      uses: actions/checkout@v4
      with:
        path: udpih

    - name: Build arm_kernel code
      run: |
        cd $GITHUB_WORKSPACE/udpih
        make arm_kernel

    - name: Upload arm_kernel code
      uses: actions/upload-artifact@v4
      with:
        name: udpih-arm_kernel
        path: ${{github.workspace}}/udpih/arm_kernel/arm_kernel.bin.h
        if-no-files-found: error

  build-pico:
    needs: build-kernel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout udpih
      uses: actions/checkout@v4
      with:
        path: udpih

    - name: Checkout pico-sdk
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        ref: master
        path: pico-sdk
        submodules: recursive

    - name: Setup pico-sdk
      run: |
        sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Download arm_kernel code
      uses: actions/download-artifact@v4
      with:
        name: udpih-arm_kernel
        path: ${{github.workspace}}/udpih/arm_kernel
  
    - name: Build pico code
      run: |
        export PICO_SDK_PATH=${{github.workspace}}/pico-sdk
        cd ${{github.workspace}}/udpih/pico
        make

    - uses: actions/upload-artifact@v4
      with:
        name: udpih-pico
        path: |
          ${{github.workspace}}/udpih/pico/build_rp2040/udpih.uf2
          ${{github.workspace}}/udpih/pico/build_rp2350/udpih.uf2
        if-no-files-found: error

  build-esp32:
    needs: build-kernel
    runs-on: ubuntu-latest
    steps:
    - name: Checkout udpih
      uses: actions/checkout@v4
      with:
        path: udpih

    - name: Checkout ESP-IDF
      uses: actions/checkout@v4
      with:
        repository: espressif/esp-idf
        ref: master
        path: esp-idf
        submodules: recursive

    - name: Setup ESP-IDF
      run: |
        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        cd ${{github.workspace}}/esp-idf
        ./install.sh

    - name: Download arm_kernel code
      uses: actions/download-artifact@v4
      with:
        name: udpih-arm_kernel
        path: ${{github.workspace}}/udpih/arm_kernel

    - name: Build ESP32-S2 code
      run: |
        cd ${{github.workspace}}/udpih/esp32
        . ${{github.workspace}}/esp-idf/export.sh
        idf.py -B build_esp32-s2 set-target esp32s2
        idf.py -B build_esp32-s2 build

    - name: Build ESP32-S3 code
      run: |
        cd ${{github.workspace}}/udpih/esp32
        . ${{github.workspace}}/esp-idf/export.sh
        idf.py -B build_esp32-s3 set-target esp32s3
        idf.py -B build_esp32-s3 build

    - uses: actions/upload-artifact@v4
      with:
        name: udpih-esp32
        path: |
          ${{github.workspace}}/udpih/esp32/build_esp32-s2/flash_args
          ${{github.workspace}}/udpih/esp32/build_esp32-s2/udpih.bin
          ${{github.workspace}}/udpih/esp32/build_esp32-s2/bootloader/bootloader.bin
          ${{github.workspace}}/udpih/esp32/build_esp32-s2/partition_table/partition-table.bin
          ${{github.workspace}}/udpih/esp32/build_esp32-s3/flash_args
          ${{github.workspace}}/udpih/esp32/build_esp32-s3/udpih.bin
          ${{github.workspace}}/udpih/esp32/build_esp32-s3/bootloader/bootloader.bin
          ${{github.workspace}}/udpih/esp32/build_esp32-s3/partition_table/partition-table.bin
        if-no-files-found: error
